[package]
name = "rust_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
openssl = "0.10.35"
rdkafka = { version = "0.29.0", features = [ "ssl", "sasl"] }
sasl2-sys = { version = "*", features = [ "vendored" ] }


[dev-dependencies]
reqwest = "0.11"

[lib]
path="src/lib.rs"


[[bin]]
path = "src/main.rs"
name = "first_actix"