[package]
name = "rust_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
# openssl = "0.10"
# rdkafka = { version = "0.29.0", features = [ "ssl", "sasl"] }
# sasl2-sys = { version = "*", features = [ "vendored" ] }
sqlx = { version = "0.7", default-features = false, features = ["runtime-tokio-rustls", "macros", "postgres", "uuid", "chrono", "migrate"] }
bigdecimal = { version = "0.3.1", features = ["serde"] }
rust_decimal = "1.29"
config = "0.13.3"
# log = "0.4"
# env_logger = "0.10.0"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.3"
tracing-log = "0.2"
chrono = "0.4.26"
uuid =  { version = "1.3.4", features = ["v4", "serde"] }
secrecy = { version = "0.8", features = ["serde"] }
tracing-actix-web = "0.7.5"
tracing-opentelemetry = "0.21.0"
opentelemetry = { version = "*", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "*", features = ["rt-tokio"] }
opentelemetry-otlp = "0.13.0"
serde_json = "1.0"
autocfg = "1.0.1"
claim = "0.5"
validator = "0.16.1"
reqwest = "0.11"
lettre = { version = "0.11.1", default-features = false, features = ["smtp-transport", "tokio1-rustls-tls", "hostname", "builder", "pool", "tracing"] }
thiserror = "1"
anyhow = "1"
clap = "4.3"
argon2 = { version = "0.5", features = ["std"] }
utoipa = {version="4.1.0", features=["actix_extras", "chrono"]}
utoipa-swagger-ui = {version ="4.0.0", features=["actix-web"]}
actix-session = { version = "0.8.0", features = ["redis-rs-tls-session"] }
dotenv = "0.15.0"

[dev-dependencies]

once_cell = "1.18.0"
fake = "2.6.1"
quickcheck = "1.0.3"
quickcheck_macros = "1"
rand = "0.8.5"

[lib]
path="src/lib.rs"


[[bin]]
path = "src/main.rs"
name = "rust_test"


[[bin]]
name = "custom_commands"
path = "src/commands/main.rs"
