[package]
name = "rust_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
# openssl = "0.10"
# rdkafka = { version = "0.29.0", features = [ "ssl", "sasl"] }
# sasl2-sys = { version = "*", features = [ "vendored" ] }
sqlx = { version = "0.6", features = [ "runtime-actix-native-tls" ,"macros", "postgres", "uuid", "chrono", "migrate", "bigdecimal"] }
bigdecimal = { version = "0.3.1", features = ["serde"] }
rust_decimal = "1.29"
config = "0.13.3"
# log = "0.4"
# env_logger = "0.10.0"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.3"
tracing-log = "0.1"
chrono = "0.4.26"
uuid =  { version = "1.3.4", features = ["v4"] }
secrecy = { version = "0.8", features = ["serde"] }
tracing-actix-web = "0.7.5"
tracing-opentelemetry = "0.19.0"
opentelemetry = { version = "*", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "*", features = ["rt-tokio"] }
opentelemetry-otlp = "0.12.0"
[dev-dependencies]
reqwest = "0.11"
once_cell = "1.18.0"


[lib]
path="src/lib.rs"


[[bin]]
path = "src/main.rs"
name = "rust_test"