[package]
name = "rust_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.1"
actix-web = "4"
actix-web-actors = "4"
anyhow = "1"
argon2 = { version = "0.5", default-features = false, features = ["std"] }
async-trait = "0.1.74"
#bigdecimal = { version = "0.4", default-features = false, features = ["serde"] }
base64 = "0.21.0"
blake2 = "0.10.6"
clap = { version = "4.3", default-features = false, features=["std"]}
chrono = { version = "0.4", features = ["serde"] }
config = { version = "0.13.3", default-features = false, features = ["yaml"] }
dotenv = "0.15.0"
ed25519-dalek = {version="2.1.0"}
futures = "0.3"
futures-util = "0.3"
geocoding = { version = "0.4"}
hex = "0.4"
jsonwebtoken = "9.2"
lettre = { version = "0.11", default-features = false, features = ["smtp-transport", "tokio1-rustls-tls", "hostname", "builder", "pool", "tracing"] }
opentelemetry = { version = "*", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "*", features = ["rt-tokio"] }
opentelemetry-otlp = {version="*"}
rand = { version = "0.8", features=["std_rng"] }
redis = { version = "0.24.0", features = ["tokio-comp", "aio"] }
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
secrecy = { version = "0.8", features = ["serde"] }
serde = { version = "1.0"}
serde_json = { version = "1.0", default-features = false}
serde_with = "3.4.0"
sqlx = { version = "0.7", default-features = false, features = ["runtime-tokio-rustls", "macros", "postgres", "uuid", "chrono", "migrate", "json", "bigdecimal"] }
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1", features = ["log"] }
tracing-actix-web = "0.7.9"
tracing-bunyan-formatter = "0.3"
tracing-log = "0.2"
tracing-opentelemetry = {version="*"}
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
utoipa = {version="4.1.0", features=["actix_extras", "chrono"]}
utoipa-swagger-ui = {version ="5.0.0", features=["actix-web"]}
utoipauto = "0.1.3"
validator = {version="0.16.1", features = ["derive"]}
uuid = { version = "1.3.4", default-features = false, features = ["v4", "serde"] }
regex = "1.10.2"
lazy_static = "1.4"
actix-http =  "3"
# strum = "0.24"
# strum_macros = "0.25"
# pulsar = "6.1.0"

[dev-dependencies]
claim = "0.5"
once_cell = "1.18.0"
fake = "2.6.1"
quickcheck = "1.0.3"
quickcheck_macros = "1"
rand = "0.8.5"

[lib]
path="src/lib.rs"


[[bin]]
path = "src/main.rs"
name = "rust_test"

[profile.release]
opt-level = 3

# [[bin]]
# name = "custom_commands"
# path = "src/commands/main.rs"


