[package]
name = "rust_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0"}

sqlx = { version = "0.7", default-features = false, features = ["runtime-tokio-rustls", "macros", "postgres", "uuid", "chrono", "migrate", "json"] }
bigdecimal = { version = "0.3.1", default-features = false, features = ["serde"] }
config = { version = "0.13.3", default-features = false, features = ["yaml"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.3"
tracing-log = "0.2"
uuid =  { version = "1.3.4", default-features = false, features = ["v4", "serde"] }
secrecy = { version = "0.8", features = ["serde"] }
tracing-actix-web = "0.7.9"
tracing-opentelemetry = {version="*"}
opentelemetry = { version = "*",  features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "*", features = ["rt-tokio"] }
opentelemetry-otlp = {version="*"}
serde_json = { version = "1.0", default-features = false}
validator = {version="0.16.1", features = ["derive"]}
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
lettre = { version = "0.11.1", default-features = false, features = ["smtp-transport", "tokio1-rustls-tls", "hostname", "builder", "pool", "tracing"] }
thiserror = "1"
anyhow = "1"
clap =  { version = "4.3", default-features = false, features=["std"]}
argon2 = { version = "0.5", default-features = false, features = ["std"] }
jsonwebtoken = "9.2.0"
rand = { version = "0.8", features=["std_rng"] }
chrono = { version = "0.4", features = ["serde"] }
utoipa = {version="4.1.0", features=["actix_extras", "chrono"]}
utoipa-swagger-ui = {version ="5.0.0", features=["actix-web"]}
dotenv = "0.15.0"
async-trait = "0.1.74"
futures ="0.3"
futures-util = "0.3"
actix = "0.13.1"
actix-web-actors = "4"

[dev-dependencies]
claim = "0.5"
once_cell = "1.18.0"
fake = "2.6.1"
quickcheck = "1.0.3"
quickcheck_macros = "1"
rand = "0.8.5"

[lib]
path="src/lib.rs"


[[bin]]
path = "src/main.rs"
name = "rust_test"


# [[bin]]
# name = "custom_commands"
# path = "src/commands/main.rs"


